export const mockModules = [
  {
    slug: "fondements-de-la-foi",
    title: "Fondements de la Foi",
    category: "Théologie",
    description: "Une exploration profonde des bases de la foi chrétienne catholique. Ce module couvre les sacrements, la prière, la Bible et la vie spirituelle.",
    instructor: "Sœur Marie-Claire Bamba",
    duration: "12 semaines",
    lessons: 24,
    isPremium: false,
    thumbnail: "/images/module-1.jpg",
    enrolled: 142,
  },
  {
    slug: "leadership-chretien",
    title: "Leadership Chrétien",
    category: "Leadership",
    description: "Développez vos compétences de leadership à la lumière des valeurs évangéliques. Apprenez à servir votre communauté avec humilité et sagesse.",
    instructor: "Fr. Jean-Baptiste Gervais EHUY",
    duration: "8 semaines",
    lessons: 16,
    isPremium: false,
    thumbnail: "/images/module-2.jpg",
    enrolled: 89,
  },
  {
    slug: "etude-biblique-avancee",
    title: "Étude Biblique Avancée",
    category: "Bible",
    description: "Plongez dans une analyse approfondie des textes bibliques, leur contexte historique et leur application dans la vie quotidienne.",
    instructor: "Sœur Marie-Claire Bamba",
    duration: "16 semaines",
    lessons: 32,
    isPremium: true,
    thumbnail: "/images/module-3.jpg",
    enrolled: 67,
  },
  {
    slug: "vie-spirituelle",
    title: "Vie Spirituelle et Prière",
    category: "Spiritualité",
    description: "Découvrez les différentes formes de prière et de méditation chrétienne pour enrichir votre vie spirituelle quotidienne.",
    instructor: "Sœur Marie-Claire Bamba",
    duration: "6 semaines",
    lessons: 12,
    isPremium: false,
    thumbnail: "/images/module-4.jpg",
    enrolled: 198,
  },
];

export const mockCourses = [
  { id: "1", title: "Introduction à la Foi Catholique", duration: "45 min", type: "video", completed: true, isPreview: true },
  { id: "2", title: "Les Sacrements de l'Église", duration: "60 min", type: "video", completed: true, isPreview: true },
  { id: "3", title: "La Prière du Notre Père", duration: "30 min", type: "pdf", completed: false, isPreview: false },
  { id: "4", title: "La Grâce de Dieu", duration: "50 min", type: "video", completed: false, isPreview: false },
  { id: "5", title: "Les Commandements", duration: "40 min", type: "video", completed: false, isPreview: false },
  { id: "6", title: "L'Eucharistie", duration: "55 min", type: "video", completed: false, isPreview: false },
];

const defaultProgramme = [
  { time: "08h00", activity: "Accueil des participants" },
  { time: "08h30", activity: "Prière d'ouverture et louange" },
  { time: "09h00", activity: "Enseignement — Partie 1" },
  { time: "11h00", activity: "Pause" },
  { time: "11h30", activity: "Enseignement — Partie 2" },
  { time: "13h00", activity: "Déjeuner en commun" },
  { time: "14h30", activity: "Ateliers et groupes de partage" },
  { time: "17h00", activity: "Messe de clôture" },
  { time: "18h00", activity: "Fin de l'événement" },
];

export const mockEvents = [
  {
    slug: "retraite-spirituelle-2026",
    title: "Retraite Spirituelle Annuelle",
    category: "Retraite",
    date: "15 Juillet 2026",
    time: "08h00 - 18h00",
    location: "Centre Pastoral MCTD, Cocody",
    places: 50,
    placesLeft: 12,
    status: "ouvert",
    description: "Une journée de ressourcement spirituel intense avec méditation, confessions, messe et partage fraternel. Animée par Fr. Jean-Baptiste Gervais EHUY.",
    banner: "/images/event-1.jpg",
    price: "Gratuit",
    maxPlacesParPersonne: 5,
    programme: defaultProgramme,
  },
  {
    slug: "conference-famille-2026",
    title: "Conférence sur la Famille Chrétienne",
    category: "Conférence",
    date: "22 Août 2026",
    time: "09h00 - 17h00",
    location: "Grand Hall MCTD, Abidjan Plateau",
    places: 200,
    placesLeft: 87,
    status: "ouvert",
    description: "Conférence internationale sur les valeurs familiales chrétiennes avec des intervenants de renommée internationale.",
    banner: "/images/event-2.jpg",
    price: "5 000 FCFA",
    maxPlacesParPersonne: 5,
    programme: defaultProgramme,
  },
  {
    slug: "concert-louange-juin",
    title: "Concert de Louange et Adoration",
    category: "Concert",
    date: "28 Juin 2026",
    time: "19h00 - 22h00",
    location: "Église MCTD — Salle principale",
    places: 300,
    placesLeft: 0,
    status: "complet",
    description: "Une soirée de louange et d'adoration avec le groupe musical MCTD Praise et des artistes invités.",
    banner: "/images/event-3.jpg",
    price: "Gratuit",
    maxPlacesParPersonne: 5,
    programme: defaultProgramme,
  },
  {
    slug: "formation-catechistes",
    title: "Formation des Catéchistes",
    category: "Formation",
    date: "10 Septembre 2026",
    time: "08h30 - 16h30",
    location: "Salle de Formation MCTD",
    places: 40,
    placesLeft: 23,
    status: "ouvert",
    description: "Programme de formation pour les catéchistes de l'église MCTD. Méthodes pédagogiques modernes et contenu théologique actualisé.",
    banner: "/images/event-4.jpg",
    price: "Gratuit",
    maxPlacesParPersonne: 5,
    programme: defaultProgramme,
  },
];

export const mockTestimonials = [
  {
    name: "Adja Koné",
    role: "Fidèle depuis 5 ans",
    text: "MCTD a transformé ma vie spirituelle. Les formations en ligne m'ont permis d'approfondir ma foi même depuis mon lieu de travail.",
    avatar: "/avatars/1.jpg",
  },
  {
    name: "Jean-Baptiste Yao",
    role: "Membre du chœur",
    text: "La communauté MCTD est une vraie famille. J'y ai trouvé des frères et sœurs qui m'ont soutenu dans les moments difficiles.",
    avatar: "/avatars/2.jpg",
  },
  {
    name: "Marie-Thérèse Ouédraogo",
    role: "Responsable des jeunes",
    text: "Les événements organisés par MCTD sont exceptionnels. Chaque retraite est une nouvelle rencontre avec Dieu.",
    avatar: "/avatars/3.jpg",
  },
];

export const mockPastoral = [
  { name: "Fr. Jean-Baptiste Gervais EHUY", title: "Fondateur et Berger du MCTD", bio: "Porteur du mandat « Faire sortir le peuple de la pauvreté », Fr. Jean-Baptiste Gervais EHUY conduit le Ministère vers le développement intégral à la lumière de l'Évangile.", photo: "/pastoral/1.jpg" },
  { name: "Clarisse EHUY", title: "Co-fondatrice", bio: "Aux côtés de son époux depuis 1987 et mariée en 1994, Clarisse EHUY accompagne les familles et les femmes dans leur cheminement spirituel et personnel.", photo: "/pastoral/2.jpg" },
  { name: "Sœur Marie-Claire Bamba", title: "Responsable E-Learning", bio: "Docteure en sciences de l'éducation, Sœur Marie-Claire développe les programmes de formation théologique et spirituelle du MCTD.", photo: "/pastoral/3.jpg" },
];

export const mockBooks = [
  {
    id: "b1",
    slug: "vivre-de-la-vie-de-dieu",
    title: "Vivre de la Vie de Dieu",
    author: "Fr. Jean-Baptiste Gervais EHUY",
    price: 8500,
    pages: 220,
    inStock: true,
    description: "Le livre fondateur du MCTD. Un appel à laisser Dieu transformer chaque dimension de notre existence : foi, famille et travail.",
    category: "livre",
    color: "#1A3C6E",
  },
  {
    id: "b2",
    slug: "exode-interieur",
    title: "Exode Intérieur",
    author: "Fr. Jean-Baptiste Gervais EHUY",
    price: 6500,
    pages: 178,
    inStock: true,
    description: "À l'image du mandat reçu en Exode 3, 7-8, une invitation à quitter la pauvreté spirituelle pour entrer dans l'abondance de Dieu.",
    category: "livre",
    color: "#122a4e",
  },
  {
    id: "b3",
    slug: "leadership-selon-evangile",
    title: "Le Leadership selon l'Évangile",
    author: "Fr. Jean-Baptiste Gervais EHUY",
    price: 7000,
    pages: 196,
    inStock: true,
    description: "Servir sans dominer : les principes évangéliques du leadership appliqués à la famille, au travail et à la communauté.",
    category: "livre",
    color: "#C8941A",
  },
  {
    id: "b4",
    slug: "fondements-foi-catholique",
    title: "Fondements de la Foi Catholique",
    author: "Sœur Marie-Claire Bamba",
    price: 5500,
    pages: 152,
    inStock: true,
    description: "Un manuel de référence clair et accessible pour comprendre les sacrements, la prière et le dépôt de la foi.",
    category: "livre",
    color: "#2a5298",
  },
  {
    id: "b5",
    slug: "priere-du-coeur",
    title: "La Prière du Cœur",
    author: "Sœur Marie-Claire Bamba",
    price: 4500,
    pages: 128,
    inStock: false,
    description: "Méditations et exercices spirituels pour approfondir sa vie de prière quotidienne et entrer en relation intime avec Dieu.",
    category: "livre",
    color: "#1A3C6E",
  },
  {
    id: "b6",
    slug: "famille-selon-dieu",
    title: "La Famille selon Dieu",
    author: "Clarisse EHUY",
    price: 6000,
    pages: 164,
    inStock: true,
    description: "Un guide pratique et spirituel pour construire une famille enracinée dans les valeurs évangéliques, porté par l'expérience de l'auteure.",
    category: "livre",
    color: "#8b1a4a",
  },
];

export const mockMagazines = [
  {
    id: "m1",
    slug: "mctd-magazine-juin-2026",
    title: "MCTD Magazine",
    edition: "N° 12 — Juin 2026",
    theme: "La force dans l'épreuve",
    price: 1500,
    inStock: true,
    description: "Au programme : témoignages de transformation, enseignement du Père Fondateur, agenda des événements du second semestre.",
    category: "magazine",
    color: "#1A3C6E",
  },
  {
    id: "m2",
    slug: "mctd-magazine-mars-2026",
    title: "MCTD Magazine",
    edition: "N° 11 — Mars 2026",
    theme: "Renouveau de Pâques",
    price: 1500,
    inStock: true,
    description: "Spécial Carême et Pâques : parcours de conversion, méditations de la Semaine Sainte, et reportage sur les baptêmes 2026.",
    category: "magazine",
    color: "#C8941A",
  },
  {
    id: "m3",
    slug: "mctd-magazine-janvier-2026",
    title: "MCTD Magazine",
    edition: "N° 10 — Janvier 2026",
    theme: "Nouvelle année, nouvelle vie",
    price: 1500,
    inStock: true,
    description: "Rétrospective 2025, orientations pastorales pour l'année, interview exclusive de Clarisse EHUY sur la vie de famille.",
    category: "magazine",
    color: "#122a4e",
  },
  {
    id: "m4",
    slug: "bulletin-pastoral-t2-2026",
    title: "Bulletin Pastoral MCTD",
    edition: "T2 2026 — Trimestriel",
    theme: "Informations de la communauté",
    price: 0,
    inStock: true,
    description: "Le bulletin officiel de la communauté : annonces paroissiales, calendrier liturgique, comptes-rendus des groupes de prière.",
    category: "magazine",
    color: "#2a5298",
  },
  {
    id: "m5",
    slug: "cahier-formation-biblique-vol3",
    title: "Cahier de Formation Biblique",
    edition: "Volume 3 — Nouveau Testament",
    theme: "Les Épîtres de Saint Paul",
    price: 2000,
    inStock: true,
    description: "Support pédagogique accompagnant les formations e-learning MCTD. Exercices, grilles de lecture et fiches mémo.",
    category: "magazine",
    color: "#1A3C6E",
  },
  {
    id: "m6",
    slug: "revue-spirituelle-pentecote",
    title: "Revue Spirituelle MCTD",
    edition: "Hors-série — Pentecôte 2026",
    theme: "Les dons de l'Esprit Saint",
    price: 2500,
    inStock: false,
    description: "Numéro spécial consacré aux charismes et à l'action de l'Esprit Saint dans la vie ordinaire. Témoignages et réflexions théologiques.",
    category: "magazine",
    color: "#7c3a8a",
  },
];

export const mockNewsBanners: { id: string; text: string; color: string; mode: "defilant" | "clignotant"; actif: boolean }[] = [
  { id: "1", text: "Conférence spirituelle annuelle — inscriptions ouvertes !", color: "#C8941A", mode: "defilant", actif: true },
];
